//1.Get Article list [https://anybunny.tv/movie/7598/franceska-jaimes-gets-fucked-outside.html]







































GET http://localhost:3000/article?page=0&filter_slug=technology&filter_type=category&post_name=skhfkjsfjks

GET http://localhost:3000/article?page=0